{
 "title": "PostgreSQL",
 "description": "Pgsty Postgres exporter Dashboard for important postgreSQL metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "projectId", "query": { "query": "label_values(pg_up,projectId)" } },
   {
    "name": "region",
    "query": {
     "query": "label_values(pg_up{projectId=~\"$projectId\"},region)"
    }
   },
   {
    "name": "instanceId",
    "query": {
     "query": "label_values(pg_up{projectId=~\"$projectId\", region=~\"$region\"},instanceId)"
    }
   },
   {
    "name": "serviceStack",
    "query": {
     "query": "label_values(pg_up{projectId=~\"$projectId\", region=~\"$region\"},serviceStackName)"
    }
   },
   {
    "name": "serviceStackId",
    "query": {
     "query": "label_values(pg_up{instanceId=~\"$instanceId\", serviceStackName=~\"$serviceStack\"},serviceStackId)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(pg_up{serviceStackId=~\"$serviceStackId\"},instance)"
    }
   },
   {
    "name": "database",
    "query": {
     "query": "label_values(pg_activity_count{datname!~\"template.*|postgres\", instance=~\"$instance\"},datname)"
    }
   },
   { "name": "interval", "query": "30s,1m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "Global Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PostgreSQL Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(pg_version)" }
   ]
  },
  {
   "title": "Transaction rate",
   "type": "stat",
   "description": "Transactions committed + roolback per minute",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_xact_commit{instance=~\"$instance\"}[$interval]))\n+\nsum(rate(pg_db_xact_rollback{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query rate",
   "type": "stat",
   "description": "Statements executed per Minute.\n\nRequires `pg_stat_statements` extension.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_query_calls{instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Shared Buffer Hits",
   "type": "gauge",
   "description": "Shared buffer hits vs reads from disc",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_db_blks_hit{instance=~\"$instance\"})\n/\n(\n    sum(pg_db_blks_hit{instance=~\"$instance\"})\n    +\n    sum(pg_db_blks_read{instance=~\"$instance\"})\n)"
    }
   ]
  },
  {
   "title": "Connections used",
   "type": "gauge",
   "description": "Percentage of max_connections used",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(pg_db_numbackends{instance=~\"$instance\"})\n/\nsum(max by (instance) (pg_setting_max_connections{instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Commit Ratio",
   "type": "gauge",
   "description": "Transaction committed vs rollbacked",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_db_xact_commit{instance=~\"$instance\"})\n/\n(\n    sum(pg_db_xact_commit{instance=~\"$instance\"})\n    +\n    sum(pg_db_xact_rollback{instance=~\"$instance\"})\n)"
    }
   ]
  },
  {
   "title": "Max Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(pg_uptime{instance=~\"$instance\"}[$interval]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Active clients",
   "type": "stat",
   "description": "Clients executing Statements.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_activity_count{state=\"active\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Average query runtime",
   "type": "stat",
   "description": "Requires `pg_stat_statements` extension.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(pg_query_exec_time{instance=~\"$instance\"}[$interval]))\n/\nsum(delta(pg_query_calls{instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Total database size",
   "type": "stat",
   "description": "Size of all databases in $serviceStack, excluding `wal` and `log`.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg by (datname) (pg_size_bytes{instance=~\"$instance\",datname!~\"log|wal\"}))"
    }
   ]
  },
  {
   "title": "Max Replication Lag",
   "type": "stat",
   "description": "Max Replication lag behind master in seconds\n\nOnly available on a standby system.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(pg_lag{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "description": "Setting: max_connections in postgreSQL.conf\n\nFor HA clusters, shows total value between all nodes.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_setting_max_connections{instance=~\"$instance\"})"
    }
   ]
  },
  { "type": "text", "description": "Spacer", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 } },
  {
   "title": "Connections by state (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_count{instance=~\"$instance\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Connections by database (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg_activity_count{instance=~\"$instance\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "1 Minute rate of transactions committed or rollback.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_xact_commit{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(rate(pg_db_xact_rollback{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Tuples inserts/updates/deletes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_tup_inserted{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(rate(pg_db_tup_updated{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(rate(pg_db_tup_deleted{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "I/O Read/Write time",
   "type": "timeseries",
   "description": "* blk_read_time: Time spent reading data file blocks by backends in this database, in milliseconds\n* blk_write_time: Time spent writing data file blocks by backends in this database, in milliseconds\n\n`track_io_timings` needs to be activated",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(pg_db_blk_read_time{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "blk_read_time"
    },
    {
     "expr": "sum(rate(pg_db_blk_write_time{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "blk_read_time"
    }
   ]
  },
  {
   "title": "Tuples fetched/returned",
   "type": "timeseries",
   "description": "* tup_fetched: rows needed to satisfy queries\n* tup_returned: rows read/scanned",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(pg_db_tup_fetched{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(rate(pg_db_tup_returned{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "Locks by state",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by (mode) (pg_lock_count{instance=~\"$instance\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Replication lag ",
   "type": "timeseries",
   "description": "Lag behind master in seconds.\n\nOnly available on a standby System.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(pg_lag{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "lag "
    }
   ]
  },
  {
   "title": "Deadlocks by database",
   "type": "timeseries",
   "description": "Should be 0 \n\nSource: pg_stat_database\n\nWith log_lock_waits turned on, deadlocks will be logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_db_deadlocks{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Temporary files by database",
   "type": "timeseries",
   "description": "Should be 0.\n\nIf temporary files are created, it can indicate insufficient work_mem. With log_temp_files the creation of temporary files are logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_db_temp_files{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  { "title": "Database: $database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }, "repeat": "database" },
  {
   "title": "Active clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_activity_count{state=\"active\",instance=~\"$instance\",datname=\"$database\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (datname) (pg_size_bytes{instance=~\"$instance\",datname=\"$database\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction rate",
   "type": "stat",
   "description": "Transactions committed + roolback per minute",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_xact_commit{instance=~\"$instance\",datname=\"$database\"}[$interval]))\n+\nsum(rate(pg_db_xact_rollback{instance=~\"$instance\",datname=\"$database\"}[$interval]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Shared Buffer Hits",
   "type": "bargauge",
   "description": "Shared buffer hits vs reads from disc",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_db_blks_hit{instance=~\"$instance\",datname=\"$database\"})\n/\n(\n    sum(pg_db_blks_hit{instance=~\"$instance\",datname=\"$database\"})\n    +\n    sum(pg_db_blks_read{instance=~\"$instance\",datname=~\"$database\"})\n)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Commit Ratio",
   "type": "bargauge",
   "description": "Transaction committed vs rollbacked",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_db_xact_commit{instance=~\"$instance\",datname=\"$database\"})\n/\n(\n    sum(pg_db_xact_commit{instance=~\"$instance\",datname=\"$database\"})\n    +\n    sum(pg_db_xact_rollback{instance=~\"$instance\",datname=\"$database\"})\n)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Connections by state (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_count{instance=~\"$instance\",datname=\"$database\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "1 Minute rate of transactions committed or rollback.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_xact_commit{instance=~\"$instance\",datname=\"$database\"}[$interval]))",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(rate(pg_db_xact_rollback{instance=~\"$instance\",datname=\"$database\"}[$interval]))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Tuples inserts/updates/deletes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_tup_inserted{instance=~\"$instance\",datname=\"$database\"}[$interval]))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(rate(pg_db_tup_updated{instance=~\"$instance\",datname=\"$database\"}[$interval]))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(rate(pg_db_tup_deleted{instance=~\"$instance\",datname=\"$database\"}[$interval]))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "Tuples fetched/returned",
   "type": "timeseries",
   "description": "* tup_fetched: rows needed to satisfy queries\n* tup_returned: rows read/scanned",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_tup_fetched{instance=~\"$instance\",datname=\"$database\"}[$interval]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(rate(pg_db_tup_returned{instance=~\"$instance\",datname=\"$database\"}[$interval]))",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "Locks by state",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (mode) (pg_lock_count{instance=~\"$instance\",datname=\"$database\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Deadlocks by database",
   "type": "timeseries",
   "description": "Should be 0 \n\nWith log_lock_waits turned on, deadlocks will be logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_deadlocks{instance=~\"$instance\",datname=\"$database\"}[$interval]))",
     "legendFormat": "deadlocks"
    }
   ]
  },
  {
   "title": "Temporary files by database",
   "type": "timeseries",
   "description": "Should be 0.\n\nIf temporary files are created, it can indicate insufficient work_mem. With log_temp_files the creation of temporary files are logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_temp_files{instance=~\"$instance\",datname=\"$database\"}[$interval]))",
     "legendFormat": "temp_files"
    }
   ]
  }
 ]
}