{
 "title": "Service Metrics",
 "description": "Dashboard for overview of services running within Zerops.io",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "projectId",
    "query": {
     "query": "label_values(container_granted_cpu,projectId)"
    }
   },
   {
    "name": "region",
    "query": {
     "query": "label_values(container_granted_cpu{projectId=~\"$projectId\"},region)"
    }
   },
   {
    "name": "instanceId",
    "query": {
     "query": "label_values(container_granted_cpu{projectId=~\"$projectId\", region=~\"$region\"},instanceId)"
    }
   },
   {
    "name": "serviceStack",
    "query": {
     "query": "label_values(container_granted_cpu{instanceId=~\"$instanceId\"},serviceStackName)"
    }
   },
   {
    "name": "serviceStackAlt",
    "query": {
     "query": "label_values(container_granted_cpu{instanceId=~\"$instanceId\", serviceStackName!~\"build.*\\\\d+|prepare.*\\\\d+\"},serviceStackName)"
    }
   },
   {
    "name": "serviceStackId",
    "query": {
     "query": "label_values(container_granted_cpu{serviceStackName=\"$serviceStack\", instanceId=~\"$instanceId\"},serviceStackId)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(container_granted_cpu{serviceStackId=\"$serviceStackId\"},serviceName)"
    }
   },
   {
    "name": "serviceId",
    "query": {
     "query": "label_values(container_granted_cpu{serviceStackId=\"$serviceStackId\", serviceName=\"$service\"},serviceId)"
    }
   },
   {
    "name": "containers",
    "query": {
     "query": "label_values(container_granted_cpu{serviceId=\"$serviceId\"},containerName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service overview - $serviceStack/$service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU [Min / Max]",
   "type": "stat",
   "description": "CPU scaling limits for containers in this service.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "CPU" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_min_cpu{serviceId=\"$serviceId\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "service_max_cpu{serviceId=\"$serviceId\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "RAM [Min / Max]",
   "type": "stat",
   "description": "RAM scaling limits for containers in this service.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_min_ram{serviceId=\"$serviceId\"}",
     "legendFormat": "Min."
    },
    {
     "expr": "service_max_ram{serviceId=\"$serviceId\"}",
     "legendFormat": "Max."
    }
   ]
  },
  {
   "title": "Disk [Min. / Max.]",
   "type": "stat",
   "description": "Disk scaling limits for containers in this service.",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_min_disk{serviceId=\"$serviceId\"}",
     "legendFormat": "Min."
    },
    {
     "expr": "service_max_disk{serviceId=\"$serviceId\"}",
     "legendFormat": "Max."
    }
   ]
  },
  {
   "title": "CPU mode",
   "type": "stat",
   "description": "Max set to 2 instead of 1, so graph stays below the value name.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_cpu_mode{serviceId=\"$serviceId\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Containers overview - $serviceStack/$service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "CPU [Granted / Utilized]",
   "type": "stat",
   "description": "Total CPU cores granted and utilized across all containers in this service.\n\nTheoretical maximum: `CPU scaling limit × max containers`. Values may temporarily exceed this maximum during zero-downtime deployments.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "CPU" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(serviceId) (container_granted_cpu{serviceId=\"$serviceId\"})",
     "legendFormat": "Granted"
    },
    {
     "expr": "sum by(serviceId) (container_utilized_cpu{serviceId=\"$serviceId\"})",
     "legendFormat": "Utilized"
    }
   ]
  },
  {
   "title": "RAM [Granted / Utilized]",
   "type": "stat",
   "description": "Total RAM granted and utilized across all containers in this service.\n\nTheoretical maximum: `RAM scaling limit × max containers`. Values may temporarily exceed this maximum during zero-downtime deployments.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(serviceId) (container_granted_ram{serviceId=\"$serviceId\"})",
     "legendFormat": "Granted"
    },
    {
     "expr": "sum by(serviceId) (container_utilized_ram{serviceId=\"$serviceId\"})",
     "legendFormat": "Utilized"
    }
   ]
  },
  {
   "title": "Disk [Granted / Utilized]",
   "type": "stat",
   "description": "Total Disk granted and utilized across all containers in this service.\n\nTheoretical maximum: `Disk scaling limit × max containers`. Values may temporarily exceed this maximum during zero-downtime deployments.",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(serviceId) (container_granted_disk{serviceId=\"$serviceId\"})",
     "legendFormat": "Granted"
    },
    {
     "expr": "sum by(serviceId) (container_utilized_disk{serviceId=\"$serviceId\"})",
     "legendFormat": "Utilized"
    }
   ]
  },
  {
   "title": "Container counts",
   "type": "timeseries",
   "description": "Container scaling boundaries and current count for this service.\n\nShows minimum, maximum, and current container counts based on scaling configuration.\nCurrent count may temporarily exceed this maximum during zero-downtime deployments.",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "service_containers_current{serviceId=\"$serviceId\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "service_containers_min{serviceId=\"$serviceId\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "service_containers_max{serviceId=\"$serviceId\"}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Container $containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "containers" },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "CPU" } },
   "targets": [
    {
     "expr": "container_utilized_cpu{serviceId=\"$serviceId\", containerName=\"$containers\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "container_granted_cpu{serviceId=\"$serviceId\", containerName=\"$containers\"}",
     "legendFormat": "Granted"
    },
    {
     "expr": "service_min_cpu{serviceId=\"$serviceId\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "service_max_cpu{serviceId=\"$serviceId\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "container_utilized_ram{serviceId=\"$serviceId\", containerName=\"$containers\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "container_granted_ram{serviceId=\"$serviceId\", containerName=\"$containers\"}",
     "legendFormat": "Granted"
    },
    {
     "expr": "service_min_ram{serviceId=\"$serviceId\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "service_max_ram{serviceId=\"$serviceId\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "container_utilized_disk{serviceId=\"$serviceId\", containerName=\"$containers\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "container_granted_disk{serviceId=\"$serviceId\", containerName=\"$containers\"}",
     "legendFormat": "Granted"
    },
    {
     "expr": "service_min_disk{serviceId=\"$serviceId\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "service_max_disk{serviceId=\"$serviceId\"}",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}